deployment:
  tasks:
    - export DEPLOYPATH=/home/strx1956/public_html/racikkopi
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R favicon_io $DEPLOYPATH
    - /bin/cp -R imgs $DEPLOYPATH
    - /bin/cp -R android-chrome-192x192.png $DEPLOYPATH
    - /bin/cp -R android-chrome-512x512.png $DEPLOYPATH
    - /bin/cp -R apple-touch-icon.png $DEPLOYPATH
    - /bin/cp -R favicon-16x16.png $DEPLOYPATH
    - /bin/cp -R favicon-32x32.png $DEPLOYPATH
    - /bin/cp -R favicon.ico $DEPLOYPATH
